theme: jekyll-theme-minimal
title: lori jia
description: A portfolio site.
linkedin: https://www.linkedin.com/in/lori-jia-487030138/ 
cv: https://drive.google.com/open?id=1upwxRi9aQwCsv8C7pjzaielknNU4dDjJ
